<?php

/**
 * @file
 * An example field using the Field Types API.
 */

/**
 * @defgroup field_fileserver
 * @ingroup DLTS
 * @{
 *
 * Based on example module and Barry Jaspan's presentation at Drupalcon Paris,
 * @link http://acquia.com/community/resources/acquia-tv/intro-field-api-module-developers Video Presentation @endlink
 *
 * Providing a field requires:
 * - Defining a field:
 *   - hook_field_info()
 *   - hook_field_schema()
 *   - hook_field_validate()
 *   - hook_field_is_empty()
 *
 * - Defining a formatter for the field (the portion that outputs the field for
 *   display):
 *   - hook_field_formatter_info()
 *   - hook_field_formatter_view()
 *
 * - Defining a widget for the edit form:
 *   - hook_field_widget_info()
 *   - hook_field_widget_form()
 *
 * Our module defines the field in field_fileserver_field_info(),
 * field_fileserver_field_validate() and field_fileserver_field_is_empty().
 * field_fileserver_field_schema() is implemented in field_fileserver.install.
 *
 * Our module sets up a formatter in field_fileserver_field_formatter_info() and
 * field_fileserver_field_formatter_view(). These are the API hooks that present
 * formatted and themed output to the user.
 *
 * And finally, our module defines the widget in
 * field_fileserver_field_widget_info() and field_fileserver_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implementation of hook_theme().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_theme/7
 */
function field_fileserver_theme() {
  return array(
    'fileserver_image' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function field_fileserver_field_info() {
  return array(
    'field_fileserver_uri' => array(
      'label' => t('FileServer'),
      'description' => t('Allow to use files storage in a FileServer'),
      'default_widget' => 'field_fileserver_link',
      'default_formatter' => 'field_fileserver_link',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 * This hook gives us a chance to validate content that's in our
 * field. We're really only interested in the $items parameter, since
 * it holds arrays representing content in the field we've defined.
 *
 * @see field_fileserver_field_widget_error()
 */
function field_fileserver_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
	foreach ($items as $delta => $item) {
		// item must have URI
		if (!empty($item['uri'])) {
    	$pathinfo = pathinfo($item['uri']);
    	$basename = str_replace('fileserver://', '', $pathinfo['basename']);
    	$ext = pathinfo($item['uri'], PATHINFO_EXTENSION);
    	// check that we have a fileserver URI
    	if (strpos($item['uri'], 'fileserver://') === false) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'field_fileserver_invalid',
          'message' => t('Invalid scheme, make sure the URI include valid scheme (e.g., fileserver://example.jpg'),
        );
    	}
    	// check that the URI is not bigger than the allowed MySQL size for varchar with index
    	if (strlen($item['uri']) > 255) {
    		$errors[$field['field_name']][$langcode][$delta][] = array(
    			'error' => 'field_fileserver_invalid',
    			'message' => t('URI bigger than 255 character'),
    		);
    	}
    	// check that the URI contain a file extension
    	if (!$ext) {
    		$errors[$field['field_name']][$langcode][$delta][] = array(
    			'error' => 'field_fileserver_invalid',
    			'message' => t('URI dose not include a file extension'),
    		);
    	}
    	else {
    	  switch ($instance['widget']['type']) {
    		  case 'field_fileserver_text':
    		  case 'field_fileserver_link':
    			  // we only need a valid URI with a file extension
    			  // if we ever end-up with a fileserver, this will be different and
    			  // more safe/efficient.
    		  	// Drupal 7 core file.inc plus jp2 and tiff files
    		  	// see: https://api.drupal.org/api/drupal/includes%21file.inc/7
    		  	$valid_extensions = array('jpg', 'jpeg', 'gif', 'png', 'txt', 'doc', 'xls', 'pdf', 'ppt', 'pps', 'odt', 'ods', 'odp', 'jp2', 'tiff',);
    		  	// do we have a valid extension
    		  	if (!in_array($ext,$valid_extensions)) {
    		  		$errors[$field['field_name']][$langcode][$delta][] = array(
    		  		  'error' => 'field_fileserver_invalid',
    		  			'message' => t('Invalid extension found @ext', array('@ext' => $ext)),
    		  		);
    		  	}
    			  break;
    		  case 'field_fileserver_image':
    			  // check for web-safe file extentions or JP2 or TIFF
    		  	$valid_extensions = array('jpg', 'jpeg', 'gif', 'png', 'jp2', 'tiff');
    		  	if (!in_array($ext,$valid_extensions)) {
    		  		$errors[$field['field_name']][$langcode][$delta][] = array(
    		  		  'error' => 'field_fileserver_invalid',
    		  			'message' => t('Invalid mime type @mimetype', array('@mimetype' => $mimetype)),
    		  		);
    		  	}
    			  break;
    	  }
    	}
    }
	}
}

/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function field_fileserver_field_is_empty($item, $field) {
  return empty($item['uri']);
}

/**
 * Implements hook_field_formatter_info().
 *
 * We need to tell Drupal that we have two different types of formatters
 * for this field.
 *
 * @see field_fileserver_field_formatter_view()
 */
function field_fileserver_field_formatter_info() {
  return array(
    'field_fileserver_text' => array(
      'label' => t('Text field'),
      'field types' => array('field_fileserver_uri'),
    ),
  	'field_fileserver_link' => array(
  	  'label' => t('Link field'),
  		'field types' => array('field_fileserver_uri'),
    ),
  	'field_fileserver_image' => array(
  	  'label' => t('Image field'),
  	  'field types' => array('field_fileserver_uri'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Four formatters are implemented.
 * - field_fileserver_text:
 * - field_fileserver_link
 * - field_fileserver_image:
 *
 * @see field_fileserver_field_formatter_info()
 */
function field_fileserver_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
	$element = array();
  switch ($display['type']) {
    case 'field_fileserver_text':
      foreach ($items as $delta => $item) {
    	  $zebra = ($delta % 2 ==  0) ? 'even' : 'odd';
    	  $value = file_create_url($item['uri']);
    		$element[$delta] = array(
    		  '#type' => 'html_tag',
    			'#tag' => 'span',
    			'#attributes' => array(
    				'class' => array('field', 'field-fileserver', 'field-fileserver-text', $zebra),
    			),
    		  '#value' => t('@value', array('@value' => $value)),
    	  );
    	}
    	break;
    case 'field_fileserver_link':
      foreach ($items as $delta => $item) {
      	$data = unserialize($item['data']);
      	$value = (isset($data['label']) && !empty($data['label'])) ? $data['label'] : $data['url'];
    	  $zebra = ($delta % 2 ==  0) ? 'even' : 'odd';
    		$uri = file_create_url($item['uri']);
    		$element[$delta] = array(
    		  '#type' => 'html_tag',
    			'#tag' => 'a',
    			'#attributes' => array(
    			  'href' => $uri,
    				'class' => array('field', 'field-fileserver', 'field-fileserver-link', $zebra),
    			),
    			'#value' => t('@value', array('@value' => $value)),
    		);
    	}
    	break;
    case 'field_fileserver_image':
    	foreach ($items as $delta => $item) {
    		$element[$delta] = theme('fileserver_image', $item);
    	}
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_info().
 *
 * Four widgets are provided.
 * - field_fileserver_text
 * - field_fileserver_link
 * - field_fileserver_image
 *
 * These widget types will eventually show up in hook_field_widget_form,
 * where we will have to flesh them out.
 *
 * @see field_fileserver_field_widget_form()
 */
function field_fileserver_field_widget_info() {
  return array(
    'field_fileserver_text' => array(
      'label' => t('Text field'),
      'field types' => array('field_fileserver_uri'),
    ),
  	'field_fileserver_link' => array(
  	  'label' => t('Link field'),
  		'field types' => array('field_fileserver_uri'),
  	),
  	'field_fileserver_image' => array(
  	  'label' => t('Image field'),
  		'field types' => array('field_fileserver_uri'),
  	),
  );
}

/**
 * Implements hook_field_presave().
 */
function field_fileserver_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
	if ($instance['widget']['module'] == 'field_fileserver') {
	  foreach ($items as $key => $item) {
		  $data = array();
      //check for web-safe file extentions
		  $pathinfo = pathinfo($item['uri']);
		  $basename = str_replace('fileserver://', '', $pathinfo['basename']);
		  $ext = pathinfo($item['uri'], PATHINFO_EXTENSION);
		  $mimetype = file_get_mimetype($basename);
		  switch ($instance['widget']['type']) {
		  	case 'field_fileserver_text':
		  	case 'field_fileserver_link':
		  		if (!empty($item['label'])) {
		  			$data['uri'] = $item['uri'];
		  			$data['url'] = file_create_url($item['uri']);
		  			if (!empty($item['label'])) {
			        $data['label'] = $item['label'];
		        }
		      }
		  		break;
		    case 'field_fileserver_image':
		      // valid JP2 or TIFF file extentions
		      $valid_hires_extensions = array('jp2', 'tiff', 'jpg',); // test assumptions that our image server can read all JPG images
		      // valid web-safe extentions
		      $valid_websafe_extensions = array( 'jpeg', 'gif', 'png',);
		      $data['uri'] = $item['uri'];
		      if (!empty($item['label'])) {
			      $data['label'] = $item['label'];
		      }
		      $dimmensions = explode("x", $item['image_style']);
		      if (count($dimmensions) == 2) {
		        $data['width'] = $dimmensions[0];
		        $data['height'] = $dimmensions[1];
		      }
		      // do we have a valid extension?
		      // check for Hi-Res file extention
		      if (in_array($ext,$valid_hires_extensions)) {
		      	// Load Djatoka Image Server utils
		      	module_load_include('inc', 'dlts_viewer', 'inc/djatoka');
		      	// Get URL
			      $data['url'] = dlts_viewer_djatoka_url($item);
		      }
		      // check for web-safe file extention
		      elseif (in_array($ext,$valid_websafe_extensions)) {
			      $data['url'] = file_create_url($item['uri']);
		      }
		      break;
		  }
		  $items[$key]['data'] = serialize($data);
		}
	}
}

/**
 * Implements hook_field_widget_form().
 *
 * hook_widget_form() is where Drupal tells us to create form elements for
 * our field's widget.
 *
 * We provide one of four different forms, depending on the widget type of
 * the Form API item provided.
 *
 */
function field_fileserver_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
	$uri_value = isset($items[$delta]['uri']) ? trim($items[$delta]['uri']) : '';
	$data_value = isset($items[$delta]['data']) ? unserialize($items[$delta]['data']) : null;
	$uri_widget = $element;
	$data_widget = $element;
  $widget['#delta'] = $delta;
  $label_widget = array(
    '#title' => 'Label',
  	'#suffix' => '<div class="field-fileserver-label"></div>',
  	'#type' => 'textfield',
  	'#default_value' => (isset($data_value['label']) && !empty($data_value['label'])) ? $data_value['label'] : '',
  	'#attributes' => array('class' => array('edit-field-fileserver-label')),
  	'#size' => 255,
  	'#maxlength' => 255,
  	'#description' => t('File label or title'),
  );
  $element['label'] = $label_widget;
  $uri_widget += array(
    '#title' => 'File identifier',
  	'#suffix' => '<div class="field-fileserver-uri"></div>',
  	'#type' => 'textfield',
  	'#default_value' => $uri_value,
  	'#attributes' => array('class' => array('edit-field-fileserver-uri')),
  	'#size' => 255,
  	'#maxlength' => 255,
  	'#description' => t('File identifier (e.g., @identifier)', array(' @identifier' => 'fileserver://exmple.jpg')),
  );
  $element['uri'] = $uri_widget;
  $data_widget += array(
    '#type' => 'hidden',
    '#default_value' => $data_value
  );
  $element['data'] = $data_widget;
  switch ($instance['widget']['type']) {
    case 'field_fileserver_image':
    	$options = array();
    	$options['oxs'] = 'Original size';
    	// Laura's default one. Create a image style in Drupal?
    	// Ask Laura what she needs to get this working as she want.
    	$options['0x230'] = 'Scale height to 230';
    	if ($data_value['width'] && $data_value['height']) {
    		$default_image_style = $data_value['width'] . 'x' . $data_value['height'];
    	}
    	else {
    		$default_image_style = '0x230';
    	}
    	foreach (image_styles() as $key => $style) {
    		$style = image_style_load($key);
    		$slice = array_slice($style['effects'], 0, 1);
    		$effects = array_shift($slice);
    		if ($effects['name'] === 'image_scale') {
    		  $width = $effects['data']['width'];
    			$height = $effects['data']['height'];
    			$options[$width . 'x' . $height] = $style['label'];
    		}
    	}
    	$image_style_widget = array(
        '#type' => 'select',
        '#title' => t('Image style'),
        '#options' => $options, // Drupal's core style + our modules options
        '#default_value' => $default_image_style,
        '#description' => t('Select the <em>image style</em> you want to apply to this image.'),
      );
      $element['image_style'] = $image_style_widget;
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see field_example_field_validate()
 * @see form_error()
 */
function field_fileserver_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'field_fileserver_invalid':
      form_error($element, $error['message']);
      break;
  }
}

/**
 * Returns HTML for a image server from the image fileserver.
 *
 * @param $variables
 *   An associative array containing:
 *   - file: A file object to which the link will be created.
 *
 * @ingroup themeable
 */
function theme_fileserver_image($variables) {
  $data = unserialize($variables['data']);
  $attributes = array();
  $attributes['src'] = $data['url'];
  $attributes['alt'] = (isset($data['label'])) ? $data['label'] : '';
  $attributes['class'] = array('field', 'field-fileserver','field-fileserver-image');
  if ($data['width'] && is_numeric($data['width'])) {
    $attributes['width'] = $data['width'];
  }
  if ($data['height'] && is_numeric($data['width'])) {
  	$attributes['height'] = $data['height'];
  }
  return array('#type' => 'html_tag', '#tag' => 'img', '#attributes' => $attributes);
}

/**
 * @} End of "defgroup field_fileserver".
 */
